karser_recaptcha3:
    site_key: '%env(RECAPTCHA3_KEY)%'
    secret_key: '%env(RECAPTCHA3_SECRET)%'
    score_threshold: 0.5
    enabled: true  #Recaptcha is functional but doesn't allow me to sign up to the contact page more than once
